### ISSUE TITLE
Component: Clickable `Spoiler`

### ISSUE THREAD

**Issue by nndda** [nndda/Pitch#140]
**Components/tweaks description.**
Kinda like `Spoiler`, but requires the user to click.

**Prototype stylesheet and the HTML structure.**

HTML:
```html
Hi, this is
<details class="custom-hd-v2"><summary>
  blank
</summary></details>,
nice to meet you.
```

(S)CSS:
```scss
.custom-hd-v2 {
  display: inline-block;
  height: 1em;

  & > summary {
    display: flex; /* Remove the default marker */
    
    &::selection {
      background: currentColor;
    }

    /* Remove the default marker on itch app */
    &::-webkit-details-marker{
      display: none;
    }
  }

  &:not([open]) > summary {
    background: currentColor;
    cursor: pointer;
  }

  &[open] > summary {
    background: transparent;
    transition: background .5s ease;
  }
}

```

**Screenshots, sketches, or live demo.**
https://codepen.io/nnda/pen/azbREKN

**Additional notes.**
Might not be very semantic :/
