### ISSUE TITLE
Component: `Read More`

### ISSUE THREAD

**Issue by nndda** [nndda/Pitch#141]
**Components/tweaks description.**
Yet another toggle to collapse or expand contents.

**Prototype stylesheet and the HTML structure.**

HTML:
```html
<div class="custom-read-more">
  <div class="custom-content" style="height: 8em;">
    <h1>Lorem ipsum</h1>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vulputate in nunc sit amet vulputate. Mauris vitae aliquam leo, sit amet dignissim neque. Cras luctus dui at metus hendrerit laoreet. Nullam ornare ante eget leo pretium, et aliquam orci pellentesque. Mauris gravida quis sapien non consectetur. Sed massa ligula, elementum et erat a, posuere feugiat arcu. Maecenas sagittis, ante at bibendum condimentum, nisi diam finibus eros, nec aliquam enim tellus a magna. Sed ante arcu, hendrerit nec eros vel, ullamcorper ullamcorper eros. Sed rhoncus diam dolor, non blandit eros mollis eu. Praesent pharetra bibendum nisl ut feugiat.
  </div>
  <details><summary></summary></details>
</div>
```

(S)CSS:
```scss
.custom-read-more {
  &:has(> details:not([open])) > .custom-content {
    height: 5.5em;
    --mask: linear-gradient(to bottom, black 50%, transparent);
    -webkit-mask-image: var(--mask);
    mask-image: var(--mask);
  }

  &:has(> details[open]) > .custom-content {
    height: unset !important;
  }

  & > details {
    & > summary {
      display: flex; /* Remove the default marker */
      width: min-content;
      margin-top: .5em;
      white-space: nowrap;
      color: var(--l);
      text-decoration: 1px underline;
      cursor: pointer;

      /* Remove the default marker on itch app */
      &::-webkit-details-marker{
        display: none;
      }

      &::after {
        content: "Read more...";
      }
    }

    &[open] {
      & > summary::after {
        content: "Read less...";
      }
    }
  }
}
```

**Screenshots, sketches, or live demo.**
https://codepen.io/nnda/pen/OPJBwzR
