### ISSUE TITLE
Component: `Image Comparison`

### ISSUE THREAD

**Issue by nndda** [nndda/Pitch#176]
**Components/tweaks description.**
It compares two images, by sliding/moving the slider handle thingy.

**Prototype stylesheet and the HTML structure.**

HTML:
```html
<div class="custom-img-compare">
  <div>
    <img src="https://img.itch.zone/aW1nLzIxMDc4NDIzLnBuZw==/original/l07Whc.png">
  </div>

  <img src="https://img.itch.zone/aW1nLzIxMDc4NDMxLnBuZw==/original/3W4DMV.png">
</div>
```

(S)CSS
```scss
.custom-img-compare {
  position: relative;
  width: fit-content;
  padding-bottom: 1em;
  margin: auto;

  // Responsiveness
  & img {
    display: block;
    height: 100%;
  }

  & > img {
    max-width: 100%;
  }

  // Overlay image
  & > div {
    position: absolute;
    top: 0;
    left: 0;
    bottom: 0;

    max-width: 100%;
    width: 50%;

    padding-bottom: 1em;

    overflow: hidden;
    resize: horizontal;

    // Separator line
    &::after {
      content: "";
      position: absolute;
      top: 0;
      right: 0;

      height: calc(100% - .2rem);
      border-right: 2px solid var(--l);
    }

    // Slider handle 'styling'
    &::before {
      content: "";
      position: absolute;
      bottom: .2rem;
      right: calc(-.5em + 1px);

      background: var(--l);
      height: .8rem;
      width: 1.25rem;

      clip-path: circle(50%);
    }
  }
}
```

**Screenshots, sketches, or live demo.**
https://codepen.io/nnda/pen/Qwwxwjg?editors=1100

**Additional notes.**
May or may not need the `experimental` tag
