### ISSUE TITLE
Decoration: `👉👈`

### ISSUE THREAD

**Issue by nndda** [nndda/Pitch#190]
**Components/tweaks description.**
👉👈

**Prototype stylesheet and the HTML structure.**

HTML:
```html
<p style="font-size: 2em;">
  rate plzzzzz?? 🥺 <span class="custom-uwu"></span>
</p>
```

(S)CSS
```scss
.custom-uwu {
  &::before, &::after {
    content: "👉";

    display: inline-block;
    margin: 0 2px;
    transform-origin: center;

    animation: u 1.15s ease-out infinite;
  }

  &::after {
    content: "👈";
    --d: -1;
  }
}

@keyframes u {
  0%, 30%, 75%, 100% {
    transform:
      translateX(0)
      rotate(0deg);
  }

  10%, 50%  {
    transform:
      translateX( calc( 5px * var(--d, 1) ) )
      rotate( calc( 9deg * var(--d, 1) ) );
  }
}
```

**Screenshots, sketches, or live demo.**
https://codepen.io/nnda/pen/raaEwry?editors=1100
