### ISSUE TITLE
Tweak: `Fade Out Collection List`

### ISSUE THREAD

**Issue by nndda** [nndda/Pitch#191]
**Components/tweaks description.**

**Prototype stylesheet and the HTML structure.**

(S)CSS
```scss
@media ( min-width : 780px ) {
  .carousel_wrapper {
    mask: alpha linear-gradient(90deg, #fff 70%, #0000);
  }
}
```

**Screenshots, sketches, or live demo.**

**Additional notes.**
