### ISSUE TITLE
Tweak: `Profile Picture`

### ISSUE THREAD

**Issue by nndda** [nndda/Pitch#192]
**Components/tweaks description.**
This tweak will add picture to your itch.io profile page.

**Prototype stylesheet and the HTML structure.**

(S)CSS
```scss
.user_links {
  display: flex;
  align-items: end;
  row-gap: .65em;

  margin-top: calc(-96px + 20px);
}
.user_links:before {
  content: "";
  background: url(https://cdn.jsdelivr.net/gh/nndda/itchio-profile@1.2.0/assets/profile.webp) 0 0/cover;
  height: 96px;
  width: 96px;
  backdrop-filter: blur(0);
  border-radius: 9px;
}
```

**Screenshots, sketches, or live demo.**

**Additional notes.**
