### ISSUE TITLE
Tweak: `Responsive Banner`

### ISSUE THREAD

**Issue by nndda** [nndda/Pitch#194]
**Components/tweaks description.**

**Prototype stylesheet and the HTML structure.**

(S)CSS
```scss
#header > img {
  object-fit: cover;
  object-position: 50%;
}

@media (max-width: 1000px) {
  #header > img {
    height: 250px;
  }
}
```

**Screenshots, sketches, or live demo.**

**Additional notes.**
