### ISSUE TITLE
Tweak sub-item: `Author Badge — Double`

### ISSUE THREAD

**Issue by nndda** [nndda/Pitch#195]
**Components/tweaks description.**

**Prototype stylesheet and the HTML structure.**

(S)CSS
```scss
.game_comments_widget .avatar_container+.post_header>.post_author {
  display: inline-flex;
}
.game_comments_widget .avatar_container[href="https://itch.io/profile/nnda"]+.post_header>.post_author::after {
  content: "Developer";
}
.game_comments_widget .avatar_container[href="https://itch.io/profile/nnda"]+.post_header>.post_author::before {
  content: "Maintainer";
  order: 3;
}
.game_comments_widget .avatar_container+.post_header>.post_author::after,
.game_comments_widget .avatar_container+.post_header>.post_author::before {
  display:inline-block;
  background:var(--btn);
  color:var(--btn_f);
  padding:.1em .5em;
  margin-left:.5em;
  border-radius:3px;
  font-size:.9em;
  font-weight:700
}
```

**Screenshots, sketches, or live demo.**

**Additional notes.**
