### ISSUE TITLE
Component: `Dot Leaders`

### ISSUE THREAD

**Issue by nndda** [nndda/Pitch#212]
**Components/tweaks description.**

**Prototype stylesheet and the HTML structure.**

HTML:
```html
<ul class="custom-dot-leaders">
  <li>
    <span>Base game</span>
    <span>$5</span>
  </li>
  <li>
    <span>Base game + bonus content</span>
    <span>$12.5</span>
  </li>

  <li>
    <h3 style="margin: 0;">
      Supporter pack
    </h3>
  </li>

  <li>
    <ul class="custom-dot-leaders">
      <li>
        <span>Original soundtracks</span>
        <span>$6.5</span>
      </li>
      <li>
        <span>Hi-res wallpapers</span>
        <span>$7.5</span>
      </li>
      <li>
        <span>Hot dog</span>
        <span>$2</span>
      </li>
    </ul>
  </li>
</ul>
```

(S)CSS
```scss
ul.custom-dot-leaders {
  list-style: none;
  max-width: 100%;
  padding: 0;
  margin-left: 1em;

  & > li:not(:has(.custom-dot-leaders)):has(> :nth-child(2):last-child) {
    
    display: flex;
    justify-content: space-between;

    & > :last-child {
      display: flex;
      flex-grow: 1;

      &::before {
        content: "";
        flex-grow: 1;
        height: 1em;
        margin: 0 .3em;
        border-bottom: .2em dotted currentColor;
      }
    }
  }
}
```

**Screenshots, sketches, or live demo.**

**Additional notes.**
